## Nama : Rafi Izdihaar
## Nim  : 2109106053

### Import Library

In [2]:
import tensorflow as tf
import numpy as np

### Membuat Random Tensor dengan ukuran dimensi (5,5)

In [3]:
random_tensor = tf.random.normal([5,5], seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

### Membuat Prime Tensor bilangan prima dengan ukuran dimensi (5,5)

In [21]:
prima = [[2,3,5,7,11],
        [13,17,19,23,29],
        [31,37,41,43,47],
        [53,59,61,71,73],
        [79,83,89,97,101]]

prime_tensor = tf.convert_to_tensor(prima, dtype=tf.float32)
prime_tensor    

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Menampilkan dimensi dari kedua variabel diatas

In [22]:
random_tensor.shape

TensorShape([5, 5])

In [23]:
prime_tensor.shape

TensorShape([5, 5])

### Menampilkan hasil dari perhitungan aritmetika dari 2 variabel diatas (minimal 5 operator)

In [24]:
jumlah = tf.add(random_tensor,prime_tensor)
print("1. Penjumlahan : ",jumlah)

1. Penjumlahan :  tf.Tensor(
[[  1.1886818   4.4845986   5.0653296   4.557296   11.099248 ]
 [ 13.591225   17.592823   16.877071   22.277103   28.94373  ]
 [ 31.643545   36.735676   42.856632   43.56784    46.617165 ]
 [ 51.514656   60.261772   60.974693   70.73537    74.532814 ]
 [ 77.25702    82.5621     88.43399    97.32067   102.13283  ]], shape=(5, 5), dtype=float32)


In [25]:
kurang = tf.subtract(random_tensor,prime_tensor)
print("2. Pengurangan : ",kurang)

2. Pengurangan :  tf.Tensor(
[[ -2.8113182  -1.5154012  -4.9346704  -9.442704  -10.900752 ]
 [-12.408775  -16.407177  -21.122929  -23.722897  -29.05627  ]
 [-30.356455  -37.264324  -39.143368  -42.43216   -47.382835 ]
 [-54.485344  -57.738228  -61.025307  -71.26463   -71.467186 ]
 [-80.74298   -83.4379    -89.56601   -96.67933   -99.86717  ]], shape=(5, 5), dtype=float32)


In [26]:
kali = tf.multiply(random_tensor,prime_tensor)
print("3. Perkalian : ",kali)

3. Perkalian :  tf.Tensor(
[[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     -1.5436709   -18.788708    111.89541   ]
 [-137.69519     -36.345116    -50.37489      31.10492     114.41593   ]], shape=(5, 5), dtype=float32)


In [27]:
bagi = tf.divide(random_tensor,prime_tensor)
print("4. Pembagian : ",bagi)

4. Pembagian :  tf.Tensor(
[[-4.0565911e-01  4.9486625e-01  1.3065875e-02 -3.4895775e-01
   9.0225823e-03]
 [ 4.5478795e-02  3.4871940e-02 -1.1173314e-01 -3.1430315e-02
  -1.9403580e-03]
 [ 2.0759510e-02 -7.1438937e-03  4.5283735e-02  1.3205621e-02
  -8.1454450e-03]
 [-2.8025346e-02  2.1385951e-02 -4.1485377e-04 -3.7271788e-03
   2.0997450e-02]
 [-2.2063002e-02 -5.2758185e-03 -6.3596629e-03  3.3058687e-03
   1.1216149e-02]], shape=(5, 5), dtype=float32)


In [28]:
pangkat = tf.pow(random_tensor,prime_tensor)
print("5. Pangkat : ",pangkat)

5. Pangkat :  tf.Tensor(
[[ 6.58237278e-01  3.27210546e+00  1.18998764e-06 -5.18914917e+02
   9.20362137e-12]
 [ 1.07839960e-03  1.37951167e-04 -1.62845650e+06 -5.73800469e-04
  -5.72948387e-37]
 [ 1.16397109e-06 -4.15966456e-22  1.04176673e+11  2.70254808e-11
  -2.52112615e-20]
 [-1.27886054e+09  9.07514625e+05 -0.00000000e+00 -0.00000000e+00
   3.47317018e+13]
 [-1.15356923e+19 -1.71214119e-30 -1.00310215e-22  0.00000000e+00
   2.95581156e+05]], shape=(5, 5), dtype=float32)


### Menampilkan nilai Maksimal dan Minimal dari variabel random tensor

#### Nilai max dari baris dan kolom random tensor

In [29]:
tf.argmax(random_tensor,axis=0).numpy()

array([2, 0, 2, 2, 3], dtype=int64)

In [30]:
tf.argmax(random_tensor,axis=1).numpy()

array([1, 1, 2, 4, 4], dtype=int64)

#### Nilai min dari baris dan kolom random tensor

In [31]:
tf.argmin(random_tensor,axis=0).numpy()

array([4, 4, 1, 0, 2], dtype=int64)

In [32]:
tf.argmin(random_tensor,axis=1).numpy()

array([3, 2, 4, 0, 0], dtype=int64)

### Menampilkan hasil dari penggabungan variabel random_tensor dengan prime_tensor (concatenation)
#### Penggabungan baris 

In [33]:
concate1 = tf.concat([random_tensor,prime_tensor],axis=0)
concate1

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
      

#### Penggabungan kolom

In [34]:
concate2 = tf.concat([random_tensor,prime_tensor],axis=1)
concate2

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0100000e+02]], dtype=float32)>

### Menampilkan hasil sorting dari dua variabel di atas secara descending

In [35]:
tf.sort(random_tensor,direction="DESCENDING").numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

In [36]:
tf.argsort(random_tensor,direction="DESCENDING").numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [37]:
tf.sort(prime_tensor,direction="DESCENDING").numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)

In [38]:
tf.argsort(prime_tensor,direction="DESCENDING").numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])